name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: |
          npm run build && npm run export
        continue-on-error: false

      - name: Verify build output
        run: |
          if [ ! -d "./out" ]; then
            echo "Build output directory './out' does not exist. Exiting."
            exit 1
          fi

      - name: Disable Jekyll
        run: echo > ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          allow_empty_commit: false
